import { describe, test, expect } from 'bun:test';
import { getTimeZonesAt as baked07, getTimeZoneAt as bakedAt07, clearCache as clear07 } from '../impls/07-baked-rules/index.ts';
import { getTimeZonesAt as audited10, getTimeZoneAt as auditedAt10, clearCache as clear10 } from '../impls/10-audited-rules/index.ts';
import { getTimeZonesAt as baseline04, getTimeZoneAt as baselineAt04, clearCache as clear04 } from '../impls/04-live-intl/index.ts';
import { scheduleClasses, genMeta, YEAR_START, STEP_MS } from '../shared/schedule.ts';
import { alignedWith } from './aligned.ts';
import { abbrFixClasses, ABBRFIX_FROM } from '../shared/abbrfix.ts';
import { historyClasses } from '../shared/history.ts';
import { resolveClass, buildScheduleIndex } from '../shared/rules.ts';
import { zones } from '../shared/zones.ts';
import { SCHEDULE_STRIDE_DAYS, HISTORY_STRIDE_DAYS } from '../tools/gen-core.ts';

// Coverage for the historical eras (shared/history.ts) integrated into the
// rule-baking impls (07, 10). Each "tricky" instant is a case the 0.1.1
// tables got WRONG: 0.1.1's impl 07 projected the current nth-weekday /
// static rules backwards, so a pre-regime-change instant resolved to today's
// offset instead of the one actually in force. We reconstruct that exact
// 0.1.1 answer with `legacyOffset` (resolveClass alone, no history) and prove
// it diverges from ICU, while the history-backed impls now match ICU.
//
// Equivalence against live Intl is only meaningful when this runtime's ICU
// matches the one the tables were generated from (same gate as
// schedule.test.ts); Chrome-generated tables are checked in-browser.
const aligned = alignedWith(genMeta);
const testIfAligned = aligned ? test : test.skip;
// known gaps: fails today, and bun flags it the moment it starts passing so
// remediation can't land silently
const testFailingIfAligned = aligned ? test.failing : test.skip;

if (!aligned) {
  console.warn(`  [history.test] tables generated by "${genMeta.host}" != runtime; skipping live-Intl equivalence`);
}

// zones-list order -> schedule class, for reproducing the 0.1.1 (history-less)
// answer: resolveClass with the year-independent rules only.
const classIdx = buildScheduleIndex(zones, scheduleClasses);
const zoneIdx = new Map(zones.map((z, i) => [z, i]));

// signed-minutes offset, matching TimeZoneInfo.offset
function legacyOffset(zone: string, ts: number): number {
  const ci = classIdx[zoneIdx.get(zone)!]!;
  return resolveClass(scheduleClasses[ci]!, ts, YEAR_START, STEP_MS).offMin;
}

function rec(get: (t: number) => { name: string; offset: number; abbr: string }[], clear: () => void, zone: string, ts: number) {
  clear();
  return get(ts).find((z) => z.name === zone)!;
}

const icu = (zone: string, ts: number) => rec(baseline04, clear04, zone, ts);
const baked = (zone: string, ts: number) => rec(baked07, clear07, zone, ts);
const audited = (zone: string, ts: number) => rec(audited10, clear10, zone, ts);

// the single-zone getters resolve through the same cores without building or
// memoizing the whole response, so they're the ones to use when walking many
// instants (single-zone.test.ts pins them to the list getters)
const icuOff = (zone: string, ts: number) => baselineAt04(zone, ts)!.offset;
const bakedOff = (zone: string, ts: number) => bakedAt07(zone, ts)!.offset;
const auditedOff = (zone: string, ts: number) => auditedAt10(zone, ts)!.offset;

// instants where 0.1.1's backward projection produced the WRONG offset
const tricky: { label: string; zone: string; ts: number }[] = [
  // US pre-2007 DST: spring-forward was the 1st Sunday of April (Apr 3, 2005),
  // not the 2nd Sunday of March that today's rule projects — so mid-March is
  // still EST. 0.1.1 projected EDT.
  { label: 'America/New_York before pre-2007 spring-forward (2005-03-20)', zone: 'America/New_York', ts: Date.UTC(2005, 2, 20, 12) },
  // US pre-2007 DST: fall-back was the last Sunday of October (Oct 30, 2005),
  // not the 1st Sunday of November — so early November is already EST. 0.1.1
  // projected EDT.
  { label: 'America/New_York after pre-2007 fall-back (2005-11-01)', zone: 'America/New_York', ts: Date.UTC(2005, 10, 1, 12) },
  // Bangladesh observed DST only in 2009 (+07); the current table has no DST
  // for Dhaka, so 0.1.1 projected the +06 standard offset year-round. This is
  // also the single-year rule whose 2nd transition wrapped past year-end and
  // is baked as a raw-year era.
  { label: 'Asia/Dhaka during its one-off 2009 DST (+07)', zone: 'Asia/Dhaka', ts: Date.UTC(2009, 7, 15, 6) },
  // Pacific/Kosrae ran at +12 until 1999-01-01, then switched to +11 (its
  // current, static offset). 0.1.1's static class projected +11 back through
  // the 1990s; the late-Dec year-end transition also stressed the generator's
  // per-year signature probe.
  { label: 'Pacific/Kosrae in its pre-1999 +12 era', zone: 'Pacific/Kosrae', ts: Date.UTC(1998, 5, 15, 12) },
  // Cambridge_Bay spent the 2000 Nunavut experiment on Eastern time (-300)
  // while its modern class is Mountain (-420/-360), so 0.1.1 projected -360
  // for this week. See the dedicated block below for why this week in
  // particular is the one that pins the generator's scan stride.
  { label: 'America/Cambridge_Bay during the 2000 Nunavut experiment (EST)', zone: 'America/Cambridge_Bay', ts: Date.UTC(2000, 10, 1, 12) },
];

// ordinary historical instants: the projection was already right here
// (post-2007 US, EU stable since 1996, southern summer), so history defers to
// the schedule and nothing regressed.
const normal: { label: string; zone: string; ts: number }[] = [
  { label: 'America/New_York summer 2015 (EDT)', zone: 'America/New_York', ts: Date.UTC(2015, 6, 15, 12) },
  { label: 'America/New_York winter 2015 (EST)', zone: 'America/New_York', ts: Date.UTC(2015, 0, 15, 12) },
  { label: 'Europe/London summer 2000 (BST, EU stable since 1996)', zone: 'Europe/London', ts: Date.UTC(2000, 6, 15, 12) },
  { label: 'Europe/Paris summer 2015 (CEST)', zone: 'Europe/Paris', ts: Date.UTC(2015, 6, 15, 12) },
  { label: 'Australia/Sydney summer 2015 (AEDT)', zone: 'Australia/Sydney', ts: Date.UTC(2015, 0, 15, 0) },
];

// Stable historical transitions with shapes that are easy for a sampled
// history generator to miss: Boa Vista changed and returned within one week,
// while Apia skipped an entire civil day by jumping across the date line.
const unusualEdges: { label: string; zone: string; ts: number; before: number; after: number }[] = [
  { label: 'Boa Vista starts its one-week DST experiment', zone: 'America/Boa_Vista', ts: Date.UTC(2000, 9, 8, 4), before: -240, after: -180 },
  { label: 'Boa Vista ends its one-week DST experiment', zone: 'America/Boa_Vista', ts: Date.UTC(2000, 9, 15, 3), before: -180, after: -240 },
  { label: 'Apia skips 2011-12-30 across the date line', zone: 'Pacific/Apia', ts: Date.UTC(2011, 11, 30, 10), before: -600, after: 840 },
];

describe('unusual historical transition boundaries are exact', () => {
  for (const { label, zone, ts, before, after } of unusualEdges) {
    test(`${label}: shipped tables flip at the exact instant`, () => {
      for (const off of [bakedOff, auditedOff]) {
        expect(off(zone, ts - 1)).toBe(before);
        expect(off(zone, ts)).toBe(after);
      }
    });

    testIfAligned(`${label}: shipped tables match live ICU`, () => {
      expect(bakedOff(zone, ts - 1)).toBe(icuOff(zone, ts - 1));
      expect(bakedOff(zone, ts)).toBe(icuOff(zone, ts));
      expect(auditedOff(zone, ts - 1)).toBe(icuOff(zone, ts - 1));
      expect(auditedOff(zone, ts)).toBe(icuOff(zone, ts));
    });
  }
});

describe('history eras fix offsets 0.1.1 projected wrong', () => {
  for (const { label, zone, ts } of tricky) {
    testIfAligned(label, () => {
      const truth = icu(zone, ts).offset;

      // the history-backed impls agree with live ICU...
      expect(baked(zone, ts).offset).toBe(truth);
      expect(audited(zone, ts).offset).toBe(truth); // no-Temporal here => baked path

      // ...and the history-less 0.1.1 projection did NOT (regression guard:
      // if this ever stops diverging the case is no longer exercising history)
      expect(legacyOffset(zone, ts)).not.toBe(truth);
    });
  }
});

describe('ordinary historical instants stay correct (history defers to schedule)', () => {
  for (const { label, zone, ts } of normal) {
    testIfAligned(label, () => {
      const truth = icu(zone, ts);

      // full record (offset + abbr) matches live ICU for the common case
      const b = baked(zone, ts);
      expect(b.offset).toBe(truth.offset);
      expect(b.abbr).toBe(truth.abbr);
      expect(audited(zone, ts)).toEqual(b);

      // and the projection was already right here — no divergence
      expect(legacyOffset(zone, ts)).toBe(truth.offset);
    });
  }
});

// America/Cambridge_Bay's 2000 Nunavut experiment holds the tightest pair of
// consecutive transitions anywhere in tzdata: a name-only CDT -> EST flip on
// Oct 29 (the offset stays at -300) followed 6.92 days later by the real
// fall-back to CST. That 6.92d gap is the floor the generator's linear scan
// stride has to stay under — tools/tz-transition-gap.ts measures it across all
// of tzdata and asserts it against the strides imported here.
//
// A stride wide enough to bracket both transitions is where the scan runs out
// of room. It resolves several changes per window, so the danger isn't two
// transitions sharing one — it's a window whose endpoints agree while
// something happened in between, which no sampling can detect. Both ends of
// this week read -300 the moment a window spans it, so only the interior —
// what these cases walk — can catch that.
const CB = 'America/Cambridge_Bay';
const CB_NAME_FLIP = Date.UTC(2000, 9, 29, 7); // CDT -> EST; offset unchanged at -300
const CB_FALL_BACK = Date.UTC(2000, 10, 5, 5); // EST -> CST; -300 -> -360

describe('the tightest transition pair in tzdata (America/Cambridge_Bay, 2000)', () => {
  testIfAligned('the name-only CDT -> EST flip leaves the offset alone', () => {
    for (const ts of [CB_NAME_FLIP - STEP_MS, CB_NAME_FLIP]) {
      expect(icuOff(CB, ts)).toBe(-300);
      expect(bakedOff(CB, ts)).toBe(-300);
      expect(auditedOff(CB, ts)).toBe(-300);
    }
  });

  testIfAligned('the whole 6.92d week between the two transitions stays at -300', () => {
    for (let ts = CB_NAME_FLIP; ts < CB_FALL_BACK; ts += STEP_MS) {
      expect(icuOff(CB, ts)).toBe(-300);
      expect(bakedOff(CB, ts)).toBe(-300);
      expect(auditedOff(CB, ts)).toBe(-300);
    }
  });

  testIfAligned('the fall-back edge is exact to the 15-minute step', () => {
    for (const off of [icuOff, bakedOff, auditedOff]) {
      expect(off(CB, CB_FALL_BACK - STEP_MS)).toBe(-300);
      expect(off(CB, CB_FALL_BACK)).toBe(-360);
    }
  });

  // guards the strategy itself rather than its current output: the cases above
  // only prove the scan resolves this pair today, and they'd keep passing if a
  // future stride change re-broke a DIFFERENT zone's tight pair
  test('the generator scans finer than this gap', () => {
    const gapDays = (CB_FALL_BACK - CB_NAME_FLIP) / 86_400_000;

    expect(gapDays).toBeCloseTo(6.92, 2);
    expect(SCHEDULE_STRIDE_DAYS).toBeLessThan(gapDays);
    expect(HISTORY_STRIDE_DAYS).toBeLessThan(gapDays);
  });
});

// The Atlantic Canada zones switched DST at 00:01 local wall time — not the
// usual 02:00 — until 2011, and Antarctica/Casey did the same in 2020-22. That
// is the one real shape that misses the generator's 15-minute step grid, and it
// used to be rounded UP: the fitted rule said 00:15, so for the first 14 minutes
// of the new offset the baked impls kept serving the old one. 93 transitions in
// the table's window, and invisible to the generator's own verification, which
// only rechecks the (already rounded) edges it recorded — it reported "0
// mismatches" the whole time this was broken.
//
// TWO independent mechanisms keep these exact, so both are pinned below —
// reverting either one alone re-breaks these instants:
//   - scanAt() times every change to the minute (gen-core refineToMinute)
//   - history rule tuples carry wall MINUTES, not quarter-hours (emitters.ts
//     tupleRef / decode.ts tupleRule); quarter-hours cannot encode atMin = 1
//
// tools/tz-transition-gap.ts reports the whole population in its "off-grid"
// column. The census test is what notices a NEW zone joining the club.
const MINUTE_MS = 60_000;

const OFF_GRID_ZONES = ['America/Goose_Bay', 'America/Moncton', 'America/St_Johns', 'Antarctica/Casey'];

const offGrid: { zone: string; ts: number; before: number; after: number }[] = [
  // first spring/fall pair of the era, and the last one before the 2011 switch
  { zone: 'America/Goose_Bay', ts: Date.UTC(1995, 3, 2, 4, 1), before: -240, after: -180 },
  { zone: 'America/Goose_Bay', ts: Date.UTC(1995, 9, 29, 3, 1), before: -180, after: -240 },
  { zone: 'America/Goose_Bay', ts: Date.UTC(2011, 2, 13, 4, 1), before: -240, after: -180 },
  { zone: 'America/Moncton', ts: Date.UTC(1995, 3, 2, 4, 1), before: -240, after: -180 },
  { zone: 'America/Moncton', ts: Date.UTC(2006, 9, 29, 3, 1), before: -180, after: -240 },
  // Newfoundland's half-hour offsets ride on top of the :01 transition, so the
  // instant is off BOTH the hour and the quarter-hour
  { zone: 'America/St_Johns', ts: Date.UTC(1995, 3, 2, 3, 31), before: -210, after: -150 },
  { zone: 'America/St_Johns', ts: Date.UTC(2011, 2, 13, 3, 31), before: -210, after: -150 },
  // and a modern case, long after the Atlantic zones moved to 02:00
  { zone: 'Antarctica/Casey', ts: Date.UTC(2020, 9, 3, 16, 1), before: 480, after: 660 },
  { zone: 'Antarctica/Casey', ts: Date.UTC(2022, 9, 1, 16, 1), before: 480, after: 660 },
];

describe('DST transitions at 00:01 local, off the 15-minute step grid', () => {
  for (const { zone, ts, before, after } of offGrid) {
    const label = `${zone} ${new Date(ts).toISOString().slice(0, 16)}Z`;

    // ungated: these assert the SHIPPED tables' precision, so they hold whatever
    // ICU the host has (the live-Intl comparison below is the gated one)
    test(`${label} flips on the exact minute`, () => {
      expect(ts % STEP_MS).not.toBe(0); // else the case has stopped being off-grid

      for (const off of [bakedOff, auditedOff]) {
        expect(off(zone, ts - MINUTE_MS)).toBe(before);
        expect(off(zone, ts)).toBe(after);
      }
    });

    // the 14 minutes the grid used to round away — the regression itself
    testIfAligned(`${label} agrees with live ICU through the rounded-away minutes`, () => {
      for (let m = 0; m < 15; m++) {
        const t = ts + m * MINUTE_MS;

        expect(icuOff(zone, t)).toBe(after);
        expect(bakedOff(zone, t)).toBe(after);
        expect(auditedOff(zone, t)).toBe(after);
      }
    });
  }

  // Pins the tuple encoding independently of the instants above: quarter-hour
  // packing simply cannot represent atMin = 1, so a revert there fails here even
  // if refineToMinute is untouched.
  //
  // Doubles as a census. If a tzdata/ICU update gives another zone an off-grid
  // rule, this fails on the zone list — add a fixture to `offGrid` for it rather
  // than just widening the expectation.
  test('history rule eras carry wall minutes, not quarter-hours', () => {
    const oddZones = new Set<string>();
    const oddMins = new Set<number>();

    for (const c of historyClasses) {
      for (const e of c.eras) {
        if (e.kind !== 1 || e.rules === null) continue;

        for (const r of e.rules) {
          // a wall-clock minute-of-day, which is what the 3-char base-36 field holds
          expect(r.atMin).toBeGreaterThanOrEqual(0);
          expect(r.atMin).toBeLessThan(1440);

          if (r.atMin % 15 !== 0) {
            oddMins.add(r.atMin);
            for (const z of c.zones) oddZones.add(z);
          }
        }
      }
    }

    expect([...oddZones].sort()).toEqual(OFF_GRID_ZONES);

    // every off-grid rule in the table today is the same 00:01 shape
    expect([...oddMins]).toEqual([1]);
  });
});

// The history table stores offsets only, so below the bake year an abbreviation
// is a pure function of the resolved offset (rules.ts historyAbbr):
//
//   const abbr = ci < 0 ? gmtLabel(off) : historyAbbr(scheduleClasses[ci]!, off);
//
// One label per run of constant offset, in other words. That is wrong two ways.
// A name-only transition splits such a run into differently-named halves, and
// more commonly, a zone whose historical identity differs from the one its
// modern schedule class describes gets that class's label for years at a time.
//
// shared/abbrfix.ts corrects the spans where the offset-keyed answer is a
// confident LIE — where it names an identity the zone has since left. Spans
// where the historical offset matches no modern state, and the fallback is a
// vague GMT±N, are deliberately left uncorrected (see the block after this one).
//
// These two tables are the regression fixtures for that overlay. Offsets must
// come through untouched: the correction replaces the label only.
const nameOnly: { label: string; zone: string; ts: number; before: string; after: string; offset: number }[] = [
  // Ciudad_Juarez sat on Central in 1998; its modern class is Mountain, and
  // -360 collides with that class's DST state
  { label: 'America/Ciudad_Juarez CST -> MPDT (1998)', zone: 'America/Ciudad_Juarez', ts: Date.UTC(1998, 3, 5, 9), before: 'CST', after: 'MPDT', offset: -360 },
  // Argentina held -180 across this flip and the one back to ART in Mar 2000,
  // so no offset change re-derives the label for over a year
  { label: 'America/Argentina/Buenos_Aires ART -> AST (1999)', zone: 'America/Argentina/Buenos_Aires', ts: Date.UTC(1999, 9, 3, 3), before: 'ART', after: 'AST', offset: -180 },
  // Libya left CEST for a permanent EET without moving off +120
  { label: 'Africa/Tripoli CEST -> EET (1997)', zone: 'Africa/Tripoli', ts: Date.UTC(1997, 9, 3, 22), before: 'CEST', after: 'EET', offset: 120 },
  // the handover renamed Macau time; +480 never budged
  { label: 'Asia/Macau MST -> CST (1999 handover)', zone: 'Asia/Macau', ts: Date.UTC(1999, 11, 19, 16), before: 'MST', after: 'CST', offset: 480 },
  { label: 'Pacific/Guam GST -> ChST (2000)', zone: 'Pacific/Guam', ts: Date.UTC(2000, 11, 22, 14), before: 'GST', after: 'ChST', offset: 600 },
  // Metlakatla left Alaska DST for Pacific standard at the same -480
  { label: 'America/Metlakatla AKDT -> PST (2018)', zone: 'America/Metlakatla', ts: Date.UTC(2018, 10, 4, 10), before: 'AKDT', after: 'PST', offset: -480 },
  // the Yukon's permanent-DST switch: -420 was relabelled from PDT to MST
  { label: 'America/Dawson PDT -> MST (2020 permanent DST)', zone: 'America/Dawson', ts: Date.UTC(2020, 10, 1, 7), before: 'PDT', after: 'MST', offset: -420 },
];

// Long identity-drift spans, which are the bulk of what the overlay fixes and
// which the name-only fixtures above badly under-represent: most mislabelled
// spans begin at an ordinary offset change, not at a name-only flip. Instants
// are mid-span on purpose — the edges are already covered above.
const identityDrift: { label: string; zone: string; ts: number; abbr: string }[] = [
  // 20.8 years, the longest single correction in the table: Metlakatla ran on
  // Pacific time until 2015 while its modern class is Alaska
  { label: 'America/Metlakatla on Pacific time (2005)', zone: 'America/Metlakatla', ts: Date.UTC(2005, 5, 15, 12), abbr: 'PST' },
  // Knox was Eastern until 2006, then moved to Central (its modern class)
  { label: 'America/Indiana/Knox before the 2006 move to Central', zone: 'America/Indiana/Knox', ts: Date.UTC(2000, 5, 15, 12), abbr: 'EST' },
  // FET is retired — no current schedule class can supply this label, which is
  // why pointing at another class instead of storing the string wouldn't work
  { label: 'Europe/Minsk during Further-eastern European Time (2013)', zone: 'Europe/Minsk', ts: Date.UTC(2013, 0, 15, 12), abbr: 'FET' },
  // DEFER spans: no historical offset is stored at all, the schedule class
  // reproduces these years exactly and only the label is wrong. 185 of the
  // corrections are like this, so they exercise the schedule fallback path
  // rather than the historical-offset branch.
  { label: 'Asia/Macau before the 1999 handover (defer)', zone: 'Asia/Macau', ts: Date.UTC(1997, 5, 15, 12), abbr: 'MST' },
  { label: 'Pacific/Saipan on NMIT before the 2000 rename (defer)', zone: 'Pacific/Saipan', ts: Date.UTC(1997, 5, 15, 12), abbr: 'NMIT' },
  // Corrections that only exist because the audit samples the BAKED side at
  // every Jan 1 as well as at live transitions. Russia stopped changing its
  // clocks in 2011, so live sits on one label for years at a stretch while the
  // era behind it flips to a defer at a year line — an audit that only walked
  // live transitions read the baked label once, before the flip, and saw no
  // disagreement. tools/abbrfix-core.ts explains the two-sided walk; these
  // pin it, since losing it would silently shrink the overlay again.
  { label: 'Europe/Astrakhan on Moscow time (2012, past a year-line era flip)', zone: 'Europe/Astrakhan', ts: Date.UTC(2012, 5, 15, 12), abbr: 'MSK' },
  { label: 'Europe/Ulyanovsk on Moscow time (2013, past a year-line era flip)', zone: 'Europe/Ulyanovsk', ts: Date.UTC(2013, 0, 15, 12), abbr: 'MSK' },
  { label: 'Asia/Anadyr on Magadan time (2013, past a year-line era flip)', zone: 'Asia/Anadyr', ts: Date.UTC(2013, 5, 15, 12), abbr: 'MAGT' },
  // Chile's 2015 permanent-DST year, likewise invisible to a live-only walk
  { label: 'America/Punta_Arenas during permanent CLST (2015)', zone: 'America/Punta_Arenas', ts: Date.UTC(2015, 5, 15, 12), abbr: 'CLST' },
];

describe('historical labels are corrected where the offset-keyed answer would lie', () => {
  // fixture integrity, kept in its own test so that a CLDR rename can't quietly
  // satisfy the cases below by breaking their premise instead
  testIfAligned('each name-only fixture really is a name-only flip in live ICU', () => {
    for (const { label, zone, ts, before, after, offset } of nameOnly) {
      const b = icu(zone, ts - STEP_MS);
      const a = icu(zone, ts);

      // label rides along so a drifted fixture names itself in the diff
      expect([label, b.abbr, b.offset]).toEqual([label, before, offset]);
      expect([label, a.abbr, a.offset]).toEqual([label, after, offset]);
    }
  });

  for (const { label, zone, ts, before, after } of nameOnly) {
    testIfAligned(label, () => {
      for (const [at, want] of [[ts - STEP_MS, before], [ts, after]] as const) {
        const b = baked(zone, at);

        expect(b.abbr).toBe(want);
        // the overlay must not disturb the offset the history eras resolved
        expect(b.offset).toBe(icu(zone, at).offset);
        // impl 10 shares the same path below the bake year
        expect(audited(zone, at)).toEqual(b);
      }
    });
  }

  for (const { label, zone, ts, abbr } of identityDrift) {
    testIfAligned(label, () => {
      const b = baked(zone, ts);

      expect(b.abbr).toBe(abbr);
      expect(b.abbr).toBe(icu(zone, ts).abbr);
      expect(b.offset).toBe(icu(zone, ts).offset);
      expect(audited(zone, ts)).toEqual(b);
    });
  }
});

// KNOWN GAP (option B+) — where the historical offset matches NO state of the
// zone's modern class, historyAbbr() gives up and returns GMT±N. That is vague
// but not a lie, so the correction table skips those spans: covering them too
// costs roughly 3x the bytes to replace labels nobody is currently misled by.
//
// Cambridge_Bay's Nunavut experiment is the case in point. It ran on Eastern
// (-300) while its modern class is Mountain (-420/-360), so -300 matches
// neither state and both sides of the Oct 29 name-only flip come back GMT-5.
describe('labels stay vague where the offset matches no modern state', () => {
  testIfAligned('America/Cambridge_Bay reports GMT-5 across the 2000 experiment', () => {
    for (const ts of [CB_NAME_FLIP - STEP_MS, CB_NAME_FLIP]) {
      expect(baked(CB, ts).abbr).toBe('GMT-5');
      expect(baked(CB, ts).offset).toBe(-300);
    }
  });

  testFailingIfAligned('America/Cambridge_Bay CDT -> EST (2000 Nunavut experiment)', () => {
    expect(baked(CB, CB_NAME_FLIP - STEP_MS).abbr).toBe('CDT');
    expect(baked(CB, CB_NAME_FLIP).abbr).toBe('EST');
  });
});

// The four irregular-class zones are deliberately absent from history: Morocco
// and Palestine suspend DST for Ramadan, which follows the lunar calendar, so
// their behavior isn't expressible as a Gregorian rule in ANY year and baking
// them would cost raw per-year segments end to end (tools/gen-core.ts: "the
// irregular-class zones are excluded"). Historical instants therefore fall
// through to the schedule class, which answers with the bake year's shape and
// is knowingly wrong — Africa/Casablanca ran on WET until 2008, so it's off by
// an hour in 244 of 372 monthly samples.
//
// The correction table has to honor the same exclusion. Labeling these spans
// would put an authoritative name on an offset we already know is approximate,
// which reads as MORE trustworthy than the GMT±N it replaced, and these four
// zones alone were 15-19% of the payload. This block pins both halves so
// re-including them anywhere has to be a deliberate act.
const irregularZones = ['Africa/Casablanca', 'Africa/El_Aaiun', 'Asia/Gaza', 'Asia/Hebron'];

describe('irregular Ramadan-rule zones stay out of the historical layer', () => {
  test('the schedule table still classes exactly these four as irregular', () => {
    const irregular = scheduleClasses.filter((c) => c.kind === 2).flatMap((c) => c.zones);
    expect(irregular.toSorted()).toEqual(irregularZones.toSorted());
  });

  test('no correction table entry touches them', () => {
    const corrected = new Set(abbrFixClasses.flatMap((c) => c.zones));
    expect(irregularZones.filter((z) => corrected.has(z))).toEqual([]);
  });

  for (const zone of irregularZones) {
    test(`${zone} answers historical instants from the schedule projection`, () => {
      const ts = Date.UTC(2000, 5, 15, 12);
      // no history era, so the historical answer IS the year-independent one
      expect(baked(zone, ts).offset).toBe(legacyOffset(zone, ts));
    });
  }
});

// A corrected label reaches makeInfo() the same way any other does, so it must
// intern the same way: pooled on (name, offset, abbr), lazily, one frozen
// instance per distinct triple. The interesting part is that a correction can
// make two answers differ ONLY in abbr — same zone, same offset — which is
// exactly the case a pool keyed too coarsely would collapse.
describe('corrected labels intern like any other TimeZoneInfo', () => {
  // Cambridge_Bay at -360 twice over: 1999 is inside a correction record (CST),
  // 2001 is past it and keeps the offset-keyed answer (MDT)
  const CB_FIXED = Date.UTC(1999, 11, 15, 12);
  const CB_PLAIN = Date.UTC(2001, 3, 15, 12);

  test('a corrected and an uncorrected answer at one offset stay distinct', () => {
    const fixed = bakedAt07(CB, CB_FIXED)!;
    const plain = bakedAt07(CB, CB_PLAIN)!;

    expect(fixed.abbr).toBe('CST');
    expect(plain.abbr).toBe('MDT');
    expect(fixed.offset).toBe(plain.offset); // only the label separates them
    expect(fixed).not.toBe(plain);
    expect(Object.isFrozen(fixed)).toBe(true);
  });

  test('two instants inside one correction record reuse the instance', () => {
    // different record hits, same (name, offset, abbr) -> same pooled object
    expect(bakedAt07(CB, CB_FIXED)).toBe(bakedAt07(CB, Date.UTC(2000, 1, 3, 6)));
  });

  test('resolving a corrected instant repeatedly allocates nothing', () => {
    const seen = new Set<unknown>();

    for (let i = 0; i < 2000; i++) {
      seen.add(bakedAt07(CB, CB_FIXED));
      seen.add(bakedAt07(CB, CB_PLAIN));
    }

    expect(seen.size).toBe(2);
  });

  test('impl 10 shares the pool with impl 07', () => {
    expect(auditedAt10(CB, CB_FIXED)).toBe(bakedAt07(CB, CB_FIXED));
  });
});

// getTimeZonesAt() resolves each schedule / history CLASS once and reuses the
// result for every zone on it, while corrections are per zone. histCache holds
// only the offset and the correction is applied after, so the two can't mix —
// these pin that, since a cache keyed one level too coarse would hand a zone
// its sibling's label and no offset assertion would notice.
describe('per-class caches do not leak corrected labels between zones', () => {
  const sameOffsetDifferentLabel: { label: string; ts: number; pairs: [string, string][] }[] = [
    {
      label: 'schedule class, corrected zone beside an uncorrected one',
      ts: Date.UTC(2000, 5, 15, 12),
      pairs: [['America/Indiana/Knox', 'EST'], ['America/Chicago', 'CDT']],
    },
    {
      label: 'schedule class, two zones on different correction payloads',
      ts: Date.UTC(1999, 10, 15, 12),
      pairs: [['America/Argentina/Buenos_Aires', 'AST'], ['America/Argentina/San_Luis', 'WAST']],
    },
    {
      label: 'history class, two zones on different correction payloads',
      ts: Date.UTC(1999, 10, 15, 12),
      pairs: [['Asia/Anadyr', 'ANAT'], ['Asia/Kamchatka', 'PETT']],
    },
  ];

  for (const { label, ts, pairs } of sameOffsetDifferentLabel) {
    test(label, () => {
      clear07();

      const all = new Map(baked07(ts).map((i) => [i.name, i]));

      for (const [zone, abbr] of pairs) expect(all.get(zone)!.abbr).toBe(abbr);

      // the premise: identical offset, so only the label distinguishes them
      const offsets = new Set(pairs.map(([zone]) => all.get(zone)!.offset));

      expect(offsets.size).toBe(1);
    });
  }

  test('the cached all-zones path matches the uncached single-zone path', () => {
    const corrected = [...new Set(abbrFixClasses.flatMap((c) => c.zones))].toSorted();
    const disagree: string[] = [];

    expect(corrected.length).toBeGreaterThan(50);

    for (let y = ABBRFIX_FROM; y < 2026; y++) {
      // February and July straddle the DST flip in both hemispheres
      for (const month of [1, 6]) {
        const ts = Date.UTC(y, month, 15, 12);

        clear07();

        const all = new Map(baked07(ts).map((i) => [i.name, i]));

        for (const zone of corrected) {
          // identity, not equality: both paths must land on the pooled instance
          if (bakedAt07(zone, ts) !== all.get(zone)) {
            disagree.push(`${zone} @ ${new Date(ts).toISOString().slice(0, 10)}`);
          }
        }
      }
    }

    expect(disagree).toEqual([]);
  });
});

describe('era boundaries switch regimes at the right year', () => {
  // Kosrae flips +12 -> +11 across the 1999 boundary; both sides match ICU
  testIfAligned('Pacific/Kosrae +12 (1998) -> +11 (1999)', () => {
    const before = baked('Pacific/Kosrae', Date.UTC(1998, 5, 15, 12)).offset;
    const after = baked('Pacific/Kosrae', Date.UTC(1999, 5, 15, 12)).offset;

    expect(before).toBe(icu('Pacific/Kosrae', Date.UTC(1998, 5, 15, 12)).offset);
    expect(after).toBe(icu('Pacific/Kosrae', Date.UTC(1999, 5, 15, 12)).offset);
    expect(before).not.toBe(after);
  });
});
